Update readme.md and libraries.md
Kotlin/kotlin-jupyter pull request #464
Opened 2024-07-24 13:07 UTC by AlejandraPedroza

This PR contains updates to the readme.md and libraries.md docs.

2024-08-07 14:15 UTC, ileasile requested changes
I like text improvements, but also have some comments

2024-08-14 07:55 UTC, AlejandraPedroza commented on docs/README-STUB.md
> +[Jupyter Notebook](https://jupyter.org) environment. This [Kernel](https://docs.jupyter.org/en/latest/projects/kernels.html) essentially acts as a bridge between Jupyter Notebook and the Kotlin compi
I'm leaving capitalized when we refer specifically to Kotlin Kernel as per our discussion with MKT.

2024-08-14 08:00 UTC, AlejandraPedroza commented on docs/README-STUB.md
> +you can install it through [Conda](#install-with-conda), [Pip](#install-with-pip), or [sources](#install-from-sources).
What about now?

2024-08-23 18:25 UTC, ileasile commented
I merged all of your changes, thank you:
https://github.com/Kotlin/kotlin-jupyter/commit/9427cc613c6124194c9a335ede24d710c8cf9c22

You can verify README in master to check that everything looks like you expected

2024-08-23 18:25 UTC, closed without merging